CREATE TABLE knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    original_file_name VARCHAR(255) NOT NULL,
    storage_key VARCHAR(512) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    document_type VARCHAR(32) NOT NULL,
    processing_status VARCHAR(32) NOT NULL,
    extracted_text TEXT,
    extraction_error TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_knowledge_documents_storage_key UNIQUE (storage_key),
    CONSTRAINT fk_knowledge_documents_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT chk_knowledge_documents_document_type
        CHECK (document_type IN ('PDF', 'DOCX', 'TXT')),
    CONSTRAINT chk_knowledge_documents_processing_status
        CHECK (processing_status IN ('UPLOADED', 'PROCESSING', 'READY', 'FAILED')),
    CONSTRAINT chk_knowledge_documents_file_size
        CHECK (file_size >= 0)
);

CREATE INDEX idx_knowledge_documents_user_id
    ON knowledge_documents (user_id);

CREATE INDEX idx_knowledge_documents_user_status
    ON knowledge_documents (user_id, processing_status);

CREATE INDEX idx_knowledge_documents_user_created_at
    ON knowledge_documents (user_id, created_at);
