CREATE TABLE workspaces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_workspaces_owner FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE workspace_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    joined_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_workspace_members_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE,
    CONSTRAINT fk_workspace_members_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT uk_workspace_members_workspace_user UNIQUE (workspace_id, user_id),
    CONSTRAINT chk_workspace_members_role CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER'))
);

CREATE INDEX idx_workspace_members_workspace_id ON workspace_members (workspace_id);
CREATE INDEX idx_workspace_members_user_id ON workspace_members (user_id);

-- Add workspace_id to knowledge_documents and conversations
ALTER TABLE knowledge_documents ADD COLUMN workspace_id BIGINT;
ALTER TABLE conversations ADD COLUMN workspace_id BIGINT;

-- Automatic Backfill: Create a "My Workspace" for every existing user
INSERT INTO workspaces (name, owner_id, created_at, updated_at)
SELECT 'My Workspace', id, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP FROM users;

-- Automatic Backfill: Add OWNER role for every user in their respective "My Workspace"
INSERT INTO workspace_members (workspace_id, user_id, role, joined_at)
SELECT id, owner_id, 'OWNER', created_at FROM workspaces;

-- Automatic Backfill: Map existing documents to the user's "My Workspace"
UPDATE knowledge_documents kd
SET workspace_id = (SELECT w.id FROM workspaces w WHERE w.owner_id = kd.user_id LIMIT 1);

-- Automatic Backfill: Map existing conversations to the user's "My Workspace"
UPDATE conversations c
SET workspace_id = (SELECT w.id FROM workspaces w WHERE w.owner_id = c.user_id LIMIT 1);

-- Rename user_id to created_by_id in knowledge_documents and conversations to clarify intent
ALTER TABLE knowledge_documents RENAME COLUMN user_id TO created_by_id;
ALTER TABLE conversations RENAME COLUMN user_id TO created_by_id;

-- Make workspace_id NOT NULL and add foreign keys
ALTER TABLE knowledge_documents ALTER COLUMN workspace_id SET NOT NULL;
ALTER TABLE knowledge_documents ADD CONSTRAINT fk_knowledge_documents_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE;
CREATE INDEX idx_knowledge_documents_workspace_id ON knowledge_documents (workspace_id);

ALTER TABLE conversations ALTER COLUMN workspace_id SET NOT NULL;
ALTER TABLE conversations ADD CONSTRAINT fk_conversations_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces (id) ON DELETE CASCADE;
CREATE INDEX idx_conversations_workspace_id ON conversations (workspace_id);
