ALTER TABLE conversations ADD COLUMN is_pinned BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE conversations ADD COLUMN is_favorite BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE conversations ADD COLUMN is_archived BOOLEAN DEFAULT FALSE NOT NULL;
