import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, Search, ShieldCheck, Users } from 'lucide-react'
import { usersApi, type PageResponse, type UserProfile } from '../lib/api'
import { Avatar } from '../components/layout/AppShell'
import { Button, ErrorState, LoadingState } from '../components/ui/Ui'

export function AdminPage() {
  const [data, setData] = useState<PageResponse<UserProfile> | null>(null)
  const [search, setSearch] = useState('')
  const [appliedSearch, setAppliedSearch] = useState('')
  const [role, setRole] = useState('')
  const [page, setPage] = useState(0)
  const [status, setStatus] = useState<'loading' | 'error' | 'ready'>('loading')
  const load = useCallback(async (currentPage: number, currentRole: string, currentSearch: string) => { setStatus('loading'); try { const response = await usersApi.list({ page: currentPage, size: 10, search: currentSearch || undefined, role: currentRole || undefined }); setData(response.data.data); setStatus('ready') } catch { setStatus('error') } }, [])
  useEffect(() => { void load(page, role, appliedSearch) }, [page, role, appliedSearch, load])
  function submitSearch(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPage(0); setAppliedSearch(search) }
  return <div className="admin-page"><div className="page-intro"><div><p className="section-kicker">Administration</p><h2>Admin dashboard</h2><p>Manage users using the role-protected backend directory.</p></div><span className="admin-protected"><ShieldCheck size={16} />Authorized access</span></div><section className="admin-overview"><div><Users size={20} /><p>Total users</p><strong>{data?.totalElements ?? '—'}</strong><span>Live backend data</span></div><div><ShieldCheck size={20} /><p>Role hierarchy</p><strong>3</strong><span>USER · ADMIN · SUPER_ADMIN</span></div></section><section className="workspace-panel admin-users"><div className="section-heading"><div><p className="section-kicker">Directory</p><h2>User management</h2><span>Search and filter are connected to the existing `/api/users` endpoint. User mutations are not exposed by the backend.</span></div></div><form className="admin-toolbar" onSubmit={submitSearch}><label><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name or email" aria-label="Search users" /></label><select value={role} onChange={(event) => { setPage(0); setRole(event.target.value) }} aria-label="Filter by role"><option value="">All roles</option><option value="USER">User</option><option value="ADMIN">Admin</option><option value="SUPER_ADMIN">Super admin</option></select><Button type="submit" variant="secondary">Search</Button></form>{status === 'loading' ? <LoadingState label="Loading users…" /> : status === 'error' ? <ErrorState message="We couldn’t load the user directory. Confirm your account has admin access, then retry." onRetry={() => void load(page, role, appliedSearch)} /> : <><div className="user-table-wrap"><table className="user-table"><thead><tr><th>User</th><th>Email</th><th>Role</th><th>Backend actions</th></tr></thead><tbody>{data?.content.length ? data.content.map((person) => <tr key={person.id}><td><span className="user-cell"><Avatar name={person.name} /><strong>{person.name}</strong></span></td><td>{person.email}</td><td><span className={`role-badge role-${person.role.toLowerCase()}`}>{person.role.replace('_', ' ')}</span></td><td><span className="muted-cell">Not available</span></td></tr>) : <tr><td colSpan={4}><div className="table-empty">No users matched this filter.</div></td></tr>}</tbody></table></div><div className="pagination"><span>{data?.totalElements ?? 0} users</span><div><Button variant="secondary" disabled={data?.first} onClick={() => setPage((value) => Math.max(0, value - 1))}><ArrowLeft size={15} />Previous</Button><span>Page {(data?.page ?? 0) + 1} of {data?.totalPages || 1}</span><Button variant="secondary" disabled={data?.last} onClick={() => setPage((value) => value + 1)}>Next<ArrowRight size={15} /></Button></div></div></>}</section></div>
}
