import { useState } from 'react'
import { Monitor, Moon, ShieldCheck, Sun, UserRound } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { useTheme, type Theme } from '../context/ThemeContext'
import { Button, TextInput } from '../components/ui/Ui'

const items = ['General', 'Profile', 'Appearance', 'AI Preferences', 'Security', 'Data & Privacy']
export function SettingsPage() { const [active, setActive] = useState('General'); return <div className="settings-page"><div className="page-intro"><div><p className="section-kicker">Workspace controls</p><h2>Settings</h2><p>Manage your account, workspace experience, and preferences.</p></div></div><div className="settings-layout"><aside className="settings-nav">{items.map((item) => <button key={item} className={active === item ? 'active' : ''} onClick={() => setActive(item)}>{item}</button>)}</aside><section className="settings-content">{active === 'Profile' || active === 'General' ? <ProfileSettings /> : active === 'Appearance' ? <AppearanceSettings /> : <FutureSettings title={active} />}</section></div></div> }
function ProfileSettings() { const { user } = useAuth(); return <div><div className="settings-heading"><UserRound size={20} /><div><h2>Profile</h2><p>Your identity across the Enterprise AI workspace.</p></div></div><div className="settings-form"><TextInput label="Name" value={user?.name ?? ''} readOnly /><TextInput label="Email" value={user?.email ?? ''} readOnly /><p className="integration-note">Profile updates are unavailable because the current backend does not expose a profile update endpoint.</p><Button variant="secondary" disabled>Save changes</Button></div></div> }
function AppearanceSettings() { const { theme, setTheme } = useTheme(); const options: { value: Theme; label: string; icon: React.ReactNode; description: string }[] = [{ value: 'light', label: 'Light', icon: <Sun size={18} />, description: 'Use the light workspace theme.' }, { value: 'dark', label: 'Dark', icon: <Moon size={18} />, description: 'Use the dark workspace theme.' }, { value: 'system', label: 'System', icon: <Monitor size={18} />, description: 'Match your device preference.' }]; return <div><div className="settings-heading"><Sun size={20} /><div><h2>Appearance</h2><p>Choose how Enterprise AI looks on this device.</p></div></div><div className="theme-options">{options.map((option) => <button key={option.value} className={theme === option.value ? 'selected' : ''} onClick={() => setTheme(option.value)}>{option.icon}<span><strong>{option.label}</strong><small>{option.description}</small></span></button>)}</div></div> }
function FutureSettings({ title }: { title: string }) { return <div><div className="settings-heading"><ShieldCheck size={20} /><div><h2>{title}</h2><p>This section is ready for backend integration.</p></div></div><div className="integration-panel">The current backend does not expose endpoints for {title.toLowerCase()} controls. This UI intentionally does not simulate changes that cannot be saved.</div></div> }
