spring.application.name=backend
server.port=8080
spring.jpa.open-in-view=false
spring.profiles.default=dev

jwt.expiration=${JWT_EXPIRATION:86400000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
